// Code generated by protoc-gen-jsonify. DO NOT EDIT.
// source: config/service/service.proto

package service
import (
	"bytes"
	"encoding/json"
	"github.com/gogo/protobuf/jsonpb"
)

// ServiceJSONMarshaler describes the default jsonpb.Marshaler used by all
// instances of Service. This struct is safe to replace or modify but
// should not be done so concurrently.
var ServiceJSONMarshaler = new(jsonpb.Marshaler)
// MarshalJSON satisfies the encoding/json Marshaler interface. This method
// uses the more correct jsonpb package to correctly marshal the message.
func (m *Service) MarshalJSON() ([]byte, error) {
	if m == nil {
		return json.Marshal(nil)
	}
	buf := &bytes.Buffer{}
	if err := ServiceJSONMarshaler.Marshal(buf, m); err != nil {
	  return nil, err
	}
	return buf.Bytes(), nil
}
var _ json.Marshaler = (*Service)(nil)
// ServiceJSONUnmarshaler describes the default jsonpb.Unmarshaler used by all
// instances of Service. This struct is safe to replace or modify but
// should not be done so concurrently.
var ServiceJSONUnmarshaler = new(jsonpb.Unmarshaler)
// UnmarshalJSON satisfies the encoding/json Unmarshaler interface. This method
// uses the more correct jsonpb package to correctly unmarshal the message.
func (m *Service) UnmarshalJSON(b []byte) error {
	return ServiceJSONUnmarshaler.Unmarshal(bytes.NewReader(b), m)
}
var _ json.Unmarshaler = (*Service)(nil)

// EndpointJSONMarshaler describes the default jsonpb.Marshaler used by all
// instances of Endpoint. This struct is safe to replace or modify but
// should not be done so concurrently.
var EndpointJSONMarshaler = new(jsonpb.Marshaler)
// MarshalJSON satisfies the encoding/json Marshaler interface. This method
// uses the more correct jsonpb package to correctly marshal the message.
func (m *Endpoint) MarshalJSON() ([]byte, error) {
	if m == nil {
		return json.Marshal(nil)
	}
	buf := &bytes.Buffer{}
	if err := EndpointJSONMarshaler.Marshal(buf, m); err != nil {
	  return nil, err
	}
	return buf.Bytes(), nil
}
var _ json.Marshaler = (*Endpoint)(nil)
// EndpointJSONUnmarshaler describes the default jsonpb.Unmarshaler used by all
// instances of Endpoint. This struct is safe to replace or modify but
// should not be done so concurrently.
var EndpointJSONUnmarshaler = new(jsonpb.Unmarshaler)
// UnmarshalJSON satisfies the encoding/json Unmarshaler interface. This method
// uses the more correct jsonpb package to correctly unmarshal the message.
func (m *Endpoint) UnmarshalJSON(b []byte) error {
	return EndpointJSONUnmarshaler.Unmarshal(bytes.NewReader(b), m)
}
var _ json.Unmarshaler = (*Endpoint)(nil)

