// Code generated by protoc-gen-jsonify. DO NOT EDIT.
// source: config/protocol/redis/redis.proto

package redis
import (
	"bytes"
	"encoding/json"
	"github.com/gogo/protobuf/jsonpb"
)

// CompressionJSONMarshaler describes the default jsonpb.Marshaler used by all
// instances of Compression. This struct is safe to replace or modify but
// should not be done so concurrently.
var CompressionJSONMarshaler = new(jsonpb.Marshaler)
// MarshalJSON satisfies the encoding/json Marshaler interface. This method
// uses the more correct jsonpb package to correctly marshal the message.
func (m *Compression) MarshalJSON() ([]byte, error) {
	if m == nil {
		return json.Marshal(nil)
	}
	buf := &bytes.Buffer{}
	if err := CompressionJSONMarshaler.Marshal(buf, m); err != nil {
	  return nil, err
	}
	return buf.Bytes(), nil
}
var _ json.Marshaler = (*Compression)(nil)
// CompressionJSONUnmarshaler describes the default jsonpb.Unmarshaler used by all
// instances of Compression. This struct is safe to replace or modify but
// should not be done so concurrently.
var CompressionJSONUnmarshaler = new(jsonpb.Unmarshaler)
// UnmarshalJSON satisfies the encoding/json Unmarshaler interface. This method
// uses the more correct jsonpb package to correctly unmarshal the message.
func (m *Compression) UnmarshalJSON(b []byte) error {
	return CompressionJSONUnmarshaler.Unmarshal(bytes.NewReader(b), m)
}
var _ json.Unmarshaler = (*Compression)(nil)

